In [1]:

import numpy as np 	

import matplotlib.pyplot as plt

import pandas as pd	

In [2]:
dataset = pd.read_csv(r'C:\Users\Dell\Downloads\loan_data.csv')

In [3]:
dataset

person_age person_gender person_education  person_income  \
0            22.0        female           Master        71948.0   
1            21.0        female      High School        12282.0   
2            25.0        female      High School        12438.0   
3            23.0        female         Bachelor        79753.0   
4            24.0          male           Master        66135.0   
...           ...           ...              ...            ...   
44995        27.0          male        Associate        47971.0   
44996        37.0        female        Associate        65800.0   
44997        33.0          male        Associate        56942.0   
44998        29.0          male         Bachelor        33164.0   
44999        24.0          male      High School        51609.0   

       person_emp_exp person_home_ownership  loan_amnt        loan_intent  \
0                   0                  RENT    35000.0           PERSONAL   
1                   0                   OWN     1000.0          EDUCATION   
2                   3              MORTGAGE     5500.0            MEDICAL   
3                   0                  RENT    35000.0            MEDICAL   
4                   1                  RENT    35000.0            MEDICAL   
...               ...                   ...        ...                ...   
44995               6                  RENT    15000.0            MEDICAL   
44996              17                  RENT     9000.0    HOMEIMPROVEMENT   
44997               7                  RENT     2771.0  DEBTCONSOLIDATION   
44998               4                  RENT    12000.0          EDUCATION   
44999               1                  RENT     6665.0  DEBTCONSOLIDATION   

       loan_int_rate  loan_percent_income  cb_person_cred_hist_length  \
0              16.02                 0.49                         3.0   
1              11.14                 0.08                         2.0   
2              12.87                 0.44                         3.0   
3              15.23                 0.44                         2.0   
4              14.27                 0.53                         4.0   
...              ...                  ...                         ...   
44995          15.66                 0.31                         3.0   
44996          14.07                 0.14                        11.0   
44997          10.02                 0.05                        10.0   
44998          13.23                 0.36                         6.0   
44999          17.05                 0.13                         3.0   

       credit_score previous_loan_defaults_on_file  loan_status  
0               561                             No            1  
1               504                            Yes            0  
2               635                             No            1  
3               675                             No            1  
4               586                             No            1  
...             ...                            ...          ...  
44995           645                             No            1  
44996           621                             No            1  
44997           668                             No            1  
44998           604                             No            1  
44999           628                             No            1  

[45000 rows x 14 columns]

In [43]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['person_gender'] = le.fit_transform(dataset['person_gender'])
dataset['person_education'] = le.fit_transform(dataset['person_education'])
dataset['person_home_ownership'] = le.fit_transform(dataset['person_home_ownership'])
dataset['loan_intent'] = le.fit_transform(dataset['loan_intent'])
dataset['previous_loan_defaults_on_file'] = le.fit_transform(dataset['previous_loan_defaults_on_file'])

In [44]:
dataset

person_age  person_gender  person_education  person_income  \
0            22.0              0                 4        71948.0   
1            21.0              0                 3        12282.0   
2            25.0              0                 3        12438.0   
3            23.0              0                 1        79753.0   
4            24.0              1                 4        66135.0   
...           ...            ...               ...            ...   
44995        27.0              1                 0        47971.0   
44996        37.0              0                 0        65800.0   
44997        33.0              1                 0        56942.0   
44998        29.0              1                 1        33164.0   
44999        24.0              1                 3        51609.0   

       person_emp_exp  person_home_ownership  loan_amnt  loan_intent  \
0                   0                      3    35000.0            4   
1                   0                      2     1000.0            1   
2                   3                      0     5500.0            3   
3                   0                      3    35000.0            3   
4                   1                      3    35000.0            3   
...               ...                    ...        ...          ...   
44995               6                      3    15000.0            3   
44996              17                      3     9000.0            2   
44997               7                      3     2771.0            0   
44998               4                      3    12000.0            1   
44999               1                      3     6665.0            0   

       loan_int_rate  loan_percent_income  cb_person_cred_hist_length  \
0              16.02                 0.49                         3.0   
1              11.14                 0.08                         2.0   
2              12.87                 0.44                         3.0   
3              15.23                 0.44                         2.0   
4              14.27                 0.53                         4.0   
...              ...                  ...                         ...   
44995          15.66                 0.31                         3.0   
44996          14.07                 0.14                        11.0   
44997          10.02                 0.05                        10.0   
44998          13.23                 0.36                         6.0   
44999          17.05                 0.13                         3.0   

       credit_score  previous_loan_defaults_on_file  loan_status  
0               561                               0            1  
1               504                               1            0  
2               635                               0            1  
3               675                               0            1  
4               586                               0            1  
...             ...                             ...          ...  
44995           645                               0            1  
44996           621                               0            1  
44997           668                               0            1  
44998           604                               0            1  
44999           628                               0            1  

[45000 rows x 14 columns]

In [49]:
dataset.to_excel('cleandataset.xlsx',index=False)

In [50]:
df = pd.read_excel(r"C:\Users\Dell\cleandataset.xlsx")

In [51]:
df

person_age  person_gender  person_education  person_income  \
0              22              0                 4          71948   
1              21              0                 3          12282   
2              25              0                 3          12438   
3              23              0                 1          79753   
4              24              1                 4          66135   
...           ...            ...               ...            ...   
44995          27              1                 0          47971   
44996          37              0                 0          65800   
44997          33              1                 0          56942   
44998          29              1                 1          33164   
44999          24              1                 3          51609   

       person_emp_exp  person_home_ownership  loan_amnt  loan_intent  \
0                   0                      3      35000            4   
1                   0                      2       1000            1   
2                   3                      0       5500            3   
3                   0                      3      35000            3   
4                   1                      3      35000            3   
...               ...                    ...        ...          ...   
44995               6                      3      15000            3   
44996              17                      3       9000            2   
44997               7                      3       2771            0   
44998               4                      3      12000            1   
44999               1                      3       6665            0   

       loan_int_rate  loan_percent_income  cb_person_cred_hist_length  \
0              16.02                 0.49                           3   
1              11.14                 0.08                           2   
2              12.87                 0.44                           3   
3              15.23                 0.44                           2   
4              14.27                 0.53                           4   
...              ...                  ...                         ...   
44995          15.66                 0.31                           3   
44996          14.07                 0.14                          11   
44997          10.02                 0.05                          10   
44998          13.23                 0.36                           6   
44999          17.05                 0.13                           3   

       credit_score  previous_loan_defaults_on_file  loan_status  
0               561                               0            1  
1               504                               1            0  
2               635                               0            1  
3               675                               0            1  
4               586                               0            1  
...             ...                             ...          ...  
44995           645                               0            1  
44996           621                               0            1  
44997           668                               0            1  
44998           604                               0            1  
44999           628                               0            1  

[45000 rows x 14 columns]

In [52]:
X = df.drop('loan_status',axis = 1)
y = df['loan_status']

In [55]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.2, random_state=True)

In [57]:

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [60]:
X_train

array([[-0.79558155,  0.89664303, -1.17499328, ..., -0.7363931 ,
        -1.77999177, -1.01929727],
       [ 0.72435112, -1.11527103,  0.84132924, ...,  0.56567721,
        -1.54274682, -1.01929727],
       [-0.96446296,  0.89664303, -1.17499328, ..., -0.7363931 ,
        -0.07973627,  0.98106807],
       ...,
       [-0.79558155,  0.89664303, -0.50288577, ..., -0.99680716,
         0.59245776,  0.98106807],
       [-0.79558155,  0.89664303,  1.51343675, ..., -0.99680716,
         0.01911579, -1.01929727],
       [-0.62670014, -1.11527103, -1.17499328, ..., -0.99680716,
         1.20534056, -1.01929727]])

In [62]:
y_train

15505    0
26526    1
11047    0
16350    0
16933    0
        ..
43723    1
32511    0
5192     0
12172    1
33003    0
Name: loan_status, Length: 9000, dtype: int64

In [63]:
X_test

array([[ 0.89323253,  0.89664303, -1.17499328, ...,  0.30526315,
         1.24488139,  0.98106807],
       [-0.28893732,  0.89664303, -1.17499328, ..., -0.47597903,
        -0.37629246,  0.98106807],
       [ 0.04882549,  0.89664303, -0.50288577, ..., -0.21556497,
         0.82970272, -1.01929727],
       ...,
       [-0.28893732,  0.89664303, -0.50288577, ..., -0.47597903,
         0.03888621, -1.01929727],
       [-0.12005592,  0.89664303,  1.51343675, ...,  0.82609127,
         1.08671808,  0.98106807],
       [-0.62670014,  0.89664303, -0.50288577, ..., -0.99680716,
         0.01911579, -1.01929727]])

In [64]:
y_test

25275    0
12561    0
24707    1
25066    1
33429    0
        ..
43518    1
26250    0
12246    0
21910    0
165      0
Name: loan_status, Length: 36000, dtype: int64

In [65]:

# Training the Decision Tree Classification model on the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [73]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [74]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[25919  2008]
 [ 2087  5986]]


In [68]:

from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)

0.88625


In [69]:
bias = classifier.score(X_train, y_train)
bias

1.0

In [70]:
variance = classifier.score(X_test, y_test)
variance

0.88625